[build]
base = "client/"
publish = "out/"
command = "yarn next build && yarn next export"

[build.environment]
ETHEREUM_NETWORK = "rinkeby"
CONTRACT_ADDRESS = "0x1762fd547d6C286a174dD62b6A6fACFAc064A0A0"
THEGRAPH_ID = "QmVPz5stKogNjMcLPPmA6M23qYvFfddNtymamxHL2wBbWd"

[context.master.environment]
PRODUCTION = "true"
ETHEREUM_NETWORK = "mainnet"
CONTRACT_ADDRESS = "0xA133541435cAeB964f572132acd8FEAC3Ed1D80B"
THEGRAPH_ID = "QmbK3nEgsWpdwPCJn4gz7yygRfZBC6Rmzw5qa1EEL85hAh"
